@echo off
echo Building...
node "%~dp0build\builder.js" "%~dp0src\index.html" "%~dp0Core\page.html"
echo Uploading...
node node_modules/nodemcu-tool/bin/nodemcu-tool.js -p %1 -b 115200 upload Core/page.html